<?php

namespace DHLGSVBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AllocationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AllocationRepository extends EntityRepository
{
}
