<?php

namespace DHLGSVBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MieterToWohnungRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MieterToWohnungRepository extends EntityRepository
{
}
